version: "3"

services:
    minecraft:
        image:
        volume:
            - minecraftdata:/data
            - /home/Minecraft/plugins:/plugins
        ports:
            - 25565:25565
        environment:
            EULA:   "TRUE"
            TYPE: ""
            OPS: "ItsBellu"
            ENABLE_WHITELIST: "TRUE"
            ENFORCE_WHITELIST: "TRUE"
        tty: true
        stdin_open: true
        restart: unless-stopped
volumes:
    minecraftdata:
        external: true
