FROM debian:buster as jdk_full
RUN apt update && apt upgrade -y \
    && apt install wget -y \
    && wget -O server.jar https://piston-data.mojang.com/v1/objects/5b868151bd02b41319f54c8d4061b8cae84e665c/server.jar \
    && chmod +x server.jar
CMD java -jar server.jar nogui
